mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

mysite/shoplist/urls.py
from django.urls import path
from .views import ItemListView, ItemCreateView, ItemUpdateView, ItemDeleteView

app_name = "shoplist"

urlpatterns = [
    path("items/", ItemListView.as_view(), name="list_items"),
    path("items/add/", ItemCreateView.as_view(), name="add_item"),
    path("items/<int:pk>/update/", ItemUpdateView.as_view(), name="update_item"),
    path("items/<int:pk>/delete/", ItemDeleteView.as_view(), name="delete_item"),
]

mysite/shoplist/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class ShoppingListItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    count = models.IntegerField(default=1)

mysite/shoplist/forms.py
from django.forms import ModelForm
from .models import ShoppingListItem, Product


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = "name", "price"


class ShoppingListForm(ModelForm):
    class Meta:
        model = ShoppingListItem
        fields = "product", "count"

mysite/shoplist/views.py
from django.shortcuts import render, reverse, HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django_filters.views import FilterView

from .models import ShoppingListItem
from .forms import ShoppingListForm
from .filters import ShoppingListFilter

# Create your views here.


class ItemListView(FilterView):
    template_name = "shoplist/list.html"
    context_object_name = "object_list"
    filterset_class = ShoppingListFilter

    def get_user(self):
        if not self.request.user.is_anonymous:
            return self.request.user

    def get_ordering(self):
        self.order = self.request.GET.get("order", "asc")
        selected_ordering = self.request.GET.get("ordering", "count")
        if self.order == "desc":
            selected_ordering = "-" + selected_ordering
        return selected_ordering

    def get_context_data(self, *args, **kwargs):
        context = super(ItemListView, self).get_context_data(*args, **kwargs)
        context["current_order"] = self.get_ordering()
        context["order"] = self.order
        return context

    def get_queryset(self):
        return (
            ShoppingListItem.objects.all()
            .select_related("product")
            .filter(user=self.get_user())
            .order_by(self.get_ordering())
        )


class ItemCreateView(CreateView):
    template_name = "shoplist/create.html"
    model = ShoppingListItem
    fields = "product", "count"
    success_url = reverse_lazy("shoplist:list_items")

    def form_valid(self, form):
        if self.request.user.is_anonymous:
            form.instance.user = None
        else:
            form.instance.user = self.request.user
        return super().form_valid(form)


class ItemUpdateView(UpdateView):
    model = ShoppingListItem
    template_name = "shoplist/update.html"
    form_class = ShoppingListForm

    def get_success_url(self):
        return reverse("shoplist:list_items")

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class ItemDeleteView(DeleteView):
    model = ShoppingListItem
    template_name = "shoplist/delete.html"
    success_url = reverse_lazy("shoplist:list_items")

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.delete()
        return HttpResponseRedirect(success_url)

mysite/shoplist/templates/shoplist/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        Base Title
        {% endblock %}
    </title>
</head>
<body>
{% block body %}
Base Body
{% endblock %}
</body>
<footer>
    <div>

    </div>
</footer>
</html>

mysite/shoplist/templates/shoplist/create.html
{% extends 'shoplist/base.html' %}

{% block title %}
    Create item
{% endblock %}

{% block body %}
<h1>Create a new items:</h1>

<div>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
</div>
<div>
    <a href="{% url 'shoplist:list_items' %}">Back to shopping list</a>
</div>
{% endblock %}

mysite/shoplist/templates/shoplist/delete.html
{% extends 'shoplist/base.html' %}

{% block title %}
  Confirm archive {{ object.name }}
{% endblock %}

{% block body %}
  <h1>Are you sure you want to delete {{ object.product.name }}?</h1>
  <br>
  <div>
    <a href="{% url 'shoplist:list_items'%}"
    >Back to sopping list</a>
  </div>
  <br>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Delete</button>
    </form>
  </div>
{% endblock %}
>>>>>>> homework_M11

mysite/shoplist/templates/shoplist/list.html
{% extends 'shoplist/base.html' %}

{% block title %}
  Shopping list
{% endblock %}

{% block body %}
  <h1>Shopping list:</h1>
  {% if object_list %}

    <div>
       <form action="" method="get">
        {{ filter.form.as_p }}
        <input type="submit" />
        </form>
       <table border="1" cellpadding="4" cellspacing="0">

         <tr>
             <th>
                <a href="{% url 'shoplist:list_items' %}?ordering=product__name&order={% if order == 'desc' %}asc{% else %}desc{% endif %}">
                    Name(Price)</a>
             </th>
             <th>
                 <a href="{% url 'shoplist:list_items' %}?ordering=count&order={% if order == 'desc' %}asc{% else %}desc{% endif %}">
                    Count</a>
             </th>
             <th>&nbsp;</th><th>&nbsp;</th>
         </tr>

    {% for item in filter.qs %}
      <tr>
        <td>
          {{ item.product.name }}({{item.product.price}} p.)
        </td>
        <td>
          {{ item.count }}
        </td>
        <td>
          <a href="{% url 'shoplist:update_item' pk=item.pk %}">update</a>
        </td>
        <td>
          <a href="{% url 'shoplist:delete_item' pk=item.pk %}">del</a>
        </td>
      </tr>



    {% endfor %}

    </div>

  {% else %}
    <h3>No products yet</h3>
  {% endif %}

  <div>
    <a href="{% url 'shoplist:add_item' %}"
      >Add a new product</a>
  </div>
{% endblock %}

mysite/shoplist/templates/shoplist/update.html
{% extends 'shoplist/base.html' %}

{% block title %}
  Update item
{% endblock %}

{% block body %}
  <h1>Update item</h1>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Update</button>
    </form>
  </div>
  <div>
    <a href="{% url 'shoplist:list_items' %}"
    >Back to shopping list </a>
  </div>
{% endblock %}